Repository hotwired/turbo, pull requests merged in 2021-06, with the labels that each got.

#121 Actions 'after' and 'before' added. Scripts enhanced for windows usage.
  package-lock.json
  package.json
  src/core/streams/stream_actions.ts
  src/tests/fixtures/svg.svg
  src/tests/functional/visit_tests.ts
  src/tests/unit/stream_element_tests.ts
Labels: enhancement

#194 #187 Start the contribution guide
  CONTRIBUTING.md
Labels: documentation

#113 Allow a single stream response to update multiple elements
  src/core/streams/stream_actions.ts
  src/elements/stream_element.ts
  src/tests/fixtures/stream.html
  src/tests/functional/stream_tests.ts
  src/tests/helpers/functional_test_case.ts
  src/tests/server.ts
Labels: enhancement

#177 Add request interceptor
  src/core/index.ts
  src/core/request_interceptor.ts
  src/http/fetch_request.ts
  src/tests/functional/visit_tests.ts
Labels: enhancement

#192 Activate script tags from turbo frames
  src/core/drive/page_renderer.ts
  src/core/frames/frame_renderer.ts
  src/tests/fixtures/frames.html
  src/tests/fixtures/frames/body_script.html
  src/tests/fixtures/frames/body_script_2.html
  src/tests/fixtures/frames/eval_false_script.html
  src/tests/functional/frame_tests.ts
Labels: bug
